Before translate
You-Dont-Know-JS-ES/Traduccion pull request #65
Opened 2024-04-23 12:26 UTC by cquesadad

**Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).

Hola, solo he añadido un espacio detrás del título en el que estaré trabajando. 

Muchas gracias de antemano por permitirme contribuir. 

👋 ¡Saludos desde Islas Canarias!

2024-04-23 14:04 UTC, mballen-1 commented
> **Yes, I promise I've read the [Contributions Guidelines](https://github.com/getify/You-Dont-Know-JS/blob/master/CONTRIBUTING.md)** (please feel free to remove this line).
> 
> Hola, solo he añadido un espacio detrás del título en el que estaré trabajando.
> 
> Muchas gracias de antemano por permitirme contribuir.
> 
> 👋 ¡Saludos desde Islas Canarias!

¡Hola Carlos, bienvenido!

2024-04-23 17:36 UTC, cquesadad commented
Hola! 

He hecho la Traducción de la sección ###The Cast. En esta sección usa una especie de metáfora para referirse al Engine, Compiler y el Scope como una especie de actores que van a participar en el proceso. The Cast no significa nada específico en JavaScript, es solo una metáfora para referirse al "Elento" que interviene.

2024-04-29 14:50 UTC, cquesadad commented
Hola, ¿Han tenido oportunidad de revisar el contenido?

Saludos y gracias

2024-04-29 15:39 UTC, mballen-1 requested changes
Está perfecto, solo una pequeña solicitud para que dejes el ';' de la línea de código.

2024-04-29 15:39 UTC, mballen-1 commented on scope & closures/ch1.md
> +Conozcamos el elenco de los actores que interactúan para procesar el programa `var a = 2`, para que podamos entender su rol en la actuación que veremos en breve:
TODO: Dejar el ';' del snippet por favor

2024-04-29 16:42 UTC, cquesadad commented on scope & closures/ch1.md
> +Conozcamos el elenco de los actores que interactúan para procesar el programa `var a = 2`, para que podamos entender su rol en la actuación que veremos en breve:
Gracias por el apunte! Está corregido.

2024-04-29 16:43 UTC, mballen-1 approved these changes

2024-04-29 16:43 UTC, merged